language: node_js
node_js: node
script:
- npm run lint
- polymer test --skip-plugin local
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  # SAUCE_ACCESS_KEY
  - secure: T+od0XNFc4AYVD2o4T6FUu0QPXO0BRaTT5R85asliRiivN+6JZ3rz8YSqy3z5v/BSSaACPdcURjnGOvGYmOgWiyH1J6AT+5325ZaP0fmIto169hQoNGuP1/rPz25+QniSHLkNGQMAwvedCnyRbIa5xJ2P9tLQBVEb7cjj/jPdtY8arPsUEqyLZQAs3e3AscRDNxvhaxK+USsj6gS8k7AxhzuENlqYV3p8isCLU3haJHcC3mjy70Cyasmu+SPltW4dAWK9LnL3+3TB1iioj8xLjfw9wk2A1TB3KjMpAzYTe19A7DSK3OIUtMZM0Uor54kQRhgAoCkEgxcxOQ4plHD8O9Ku8/y+jrx6enfOOYifhejNufhZ5nAn1lSeZvEzlahaGDL3ImD4Ao6I1ha2DIW+GVwDpWPA32C8wAG3rAAfmSBuzZIZmK5O7qtsB1uuA/qf4xzzb00sVHOJI1cHsseVYPq9y5sgM+zNVmR2o8BShNwA7IHCR0dAmobtYp07GPB50FBlkQj0P2ZEkYkkIMtyv5ieHVlC8kZM6r1KQkFjWiXqXq7VYiDYRspl3gZ6F2Kp61t0AofSNGq6E23l/UKfWttnf2ScHM6fSPbtTI9xXfgfc6qYD72MIu52zUNQJENVUJVAn1Q2a8Jb9Pw6+V3WC/nF5pEctQ2HoXOUaMkXnM=
